### ISSUE TITLE
Impossible to provide MQTT credentials

### ISSUE THREAD

**Issue by denisvic** [JakobLichterfeld/TeslaMate_Telegram_Bot#23]
I use a separate MQTT broker with simple authentication. 
MQTT_BROKER_USERNAME and MQTT_BROKER_PASSWORD are not implemented.

**Comment by JakobLichterfeld** [comment]
Hi,

You are right, this is not yet implemented.

Had a short look seems quite easy to implement with

```
username_pw_set(username, password=None)
```
Before the connect. Need to test the behavior when no authentification is set on broker.

Regards

**Comment by JakobLichterfeld** [comment]
@denisvic : Please give the latest version a try :-)

**Comment by denisvic** [comment]
@JakobLichterfeld thank you so much !
